//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_details
    {
        public int Id { get; set; }
        public int Cust_Id { get; set; }
        public string date_of_booking { get; set; }
        public string flying_from { get; set; }
        public string moving_to { get; set; }
        public System.DateTime Departure_date { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
