//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Airline_Entities : DbContext
    {
        public Airline_Entities()
            : base("name=Airline_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_details> Booking_details { get; set; }
        public virtual DbSet<Flight_Schedule> Flight_Schedule { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
    }
}
